### ISSUE TITLE
Release 1.1.0 and changelog

### ISSUE THREAD

**Issue by ncoden** [furzeface/gulp-cache-bust#18]
@furzeface Can you add the `v1.1.0` release in https://github.com/furzeface/gulp-cache-bust/releases, with a changelog ?

Thanks.

**Comment by furzeface** [comment]
Hey @ncoden - as far as I was aware it had been [published to NPM](https://www.npmjs.com/package/gulp-cache-bust) by @davinkevin - have you been able to install it from there?

I have added [a 1.1.0 release](https://github.com/furzeface/gulp-cache-bust/releases/tag/1.1.0 ) to GitHub though: 

Is there a reason you needed it, just out of interest? Thanks for pointing out that it wasn't there, anyway 😄:octocat:

**Comment by ncoden** [comment]
I installed the `v1.1.0` release from NPM, I was just looking for a changelog :)

Thank you for adding it. I was updating the foundation-sites dependencies and needed to check if the new release would add backward incompatibilities.
